const pages = [

  // '2018-eventsattendees',
  // '2018-gresb-score-debriefs',
  // '2018-intensity-calculations',
  // '3rd-party-assurance-verification',
  // '6-proven-dashboard-views-to-drive-sustainability-results-confirmation',
  // 'aero-building-solutions',
  // 'aggregate-electric-portals',
  // 'ardem-activation',
  // 'baseline-account-set-up-for-estar-manual',
  // 'baseline-account-set-up-for-estar-pros-usync',
  // 'baseline-account-set-up-for-hybrid-properties',
  // 'baseline-account-set-up-for-limited-e-billing-customers',
  // 'baseline-account-set-up-for-manual',
  // 'baseline-account-set-up-for-users-with-multiple-energy-star-accounts',
  // 'baseline-account-set-up-for-usync-newbie',
  // 'baseline-sdr-script-for-cc',
  // 'bill-pay-providers',
  // 'boma',
  // 'brainstorm-why-corporate-occupiers-need-msr',
  // 'bulk-historical-billing-projects-via-ardem',
  // 'bulk-upload-instructions',
  // 'business-plan-go-to-market-strategy-partners',
  // 'calendarization',
  // 'categorizing-grouping-zendesk-tickets',
  // 'cbre-gws-global-workplace-solutions',
  // 'cdp-gap-analysis',
  // 'cdp-mapping-msr-to-cdp-portal',
  // 'chases-weekly-sales-reports',
  // 'client-renewals',
  // 'code-green-solutions',
  // 'company-info-for-rfp',
  // 'competitors',
  // 'conquest-pursuit-playbook-notes',
  // 'conservice',
  // 'conservice-utility-sync-activation',
  // 'consultants-master-list',
  // 'csm-quarterly-tasks',
  // 'csm-workflow-gresb',
  // 'customer-activity-channel',
  // 'customer-succes-levels-of-service',
  // 'customer-support-monthly-metrics',
  // 'data-check',
  // 'data-quality-alerts',
  // 'deal-stages-for-hubspot-current-sales-pipeline',
  // 'deal-types-in-hubspot',
  // 'drews-sdr-weekly-update',
  // 'drift-thoughts',
  // 'e4-mexican-benchmarking-platform-draft',
  // 'engaging-commercial-tenants-and-occupants-in-energy-efficiency',
  // 'enterprise-rfp-saas-process',
  // 'environmental-save',
  // 'event-planning-lifecycle',
  // 'event-process-12july2018docx',
  // 'event-strategy',
  // 'excel-diff',
  // 'explaining-measurabl-concisely-from-a-new-msr-employee',
  // 'factors-for-intensity-and-score-calcs',
  // 'feature-request-transition-plan',
  // 'filing-bug-tickets',
  // 'gabes-sdr-weekly-updates',
  // 'gdpr-compliance',
  // 'ghg-emissions-scope-123',
  // 'goby',
  // 'google-tag-manager',
  // 'green-office-tool',
  // 'green-sports-alliance',
  // 'greenofficetoolcom',
  // 'greenstone',
  // 'gresb',
  // 'gresb-2018-guidance-cheat-sheet',
  // 'gresb-asset-level-upload',
  // 'gresb-certification-approval',
  // 'gresb-final-submission-review-and-audit-process',
  // 'gresb-included-sites',
  // 'gresb-qualitative-api-feature',
  // 'gri-overview',
  // 'haley-aldrich',
  // 'hcp-insights',
  // 'historical-data-project',
  // 'how-campuses-appear-in-measurabl',
  // 'how-to-create-a-quote-in-hubspot',
  // 'how-to-find-the-leads-in-hubspot',
  // 'how-to-use-products-in-hubspot',
  // 'hubspot-crm',
  // 'hubspot-data-integrity-issues-to-fix',
  // 'hubspot-domain',
  // 'hubspot-integration',
  // 'hubspot-knowledge-transfer',

  // 'hubspot-naming-convention-changes-marketing-sales-cs',
  // 'hubspot-testing-api',
  // 'ibcon-company-attendee-list-as-of-may-23',
  // 'info-gathering-when-user-is-unhappy-with-usync',
  // 'initial-customer-training',
  // 'instructions-quick-links',
  // 'invision-process',
  // 'isos',
  // 'isos-training-2019',
  // 'isoslrqa-assurance-process',
  // 'jll-peers',
  // 'jll-sustainability',
  // 'kick-off-call',
  // 'knowledgebase-article-template-and-guidance',
  // 'known-data-issues',
  // 'list-of-events-on-our-radar',
  // 'lucid',
  // 'mach-energy',
  // 'marketing-onboarding-for-new-measurablites',
  // 'marketing-partner-program',
  // 'marketing-partners',
  // 'marketing-resources-webinars-one-pagers-etc',
  // 'marketplace-services',
  // 'measurabl-certifications',
  // 'measurabl-demo-key-facts-to-hit',
  // 'measurabl-gresb-mapping-2018',
  // 'measurabl-surveys-google-sheet-functionality',
  // 'mels-weekly-sales-reports',
  // 'metabase',
  // 'monthly-customer-support-kpi-report',
  // 'new-construction-major-renovation',
  // 'official-gresb-response-check-1',
  // 'on-boarding-process-for-new-customers-not-just-pro',
  // 'on-boarding-process-for-new-enterprise-customers',
  // 'on-boarding-roadmap-for-new-cs-team-members',
  // 'onboarding-email-template-1',
  // 'onboarding-email-template-2',
  // 'opportunity-creation-validation-process',
  // 'our-deal-flow-demo-flow-process-framework',
  // 'our-products-in-hubspot',
  // 'partners-master-list',
  // 'patrick-engineering',
  // 'post-demo-follow-up-meeting',
  // 'pricing-and-partner-structure',
  // 'pricing-validation-process',
  // 'prior-year-to-current-year-gresb-mapping',
  // 'product-backlog-prioritisation-feedback-jm',
  // 'product-committee-process',
  // 'product-feedback-jm',
  // 'projects-roll-up',
  // 'proposal-process-current-and-proposed',
  // 'quinn-and-partners-qp',
  // 'real-estatesustainability-glossary',
  // 'release-notes-for-partners-template',
  // 'resend-invitation',
  // 'response-check-gresb',
  // 's3-cheat-sheet',
  // 'sales-to-cs-workflow',
  // 'sales-transition',
  // 'schneider-electric-resource-advisor',
  // 'sdr-deal-process-workflow',
  // 'sdr-onboarding',
  // 'sdr-training-day',
  // 'sdr-weekly-meeting',
  // 'seans-weekly-sales-report',
  // 'security-phishing-helpdesk',
  // 'servidyne',
  // 'sig',
  // 'site-anomaly-detector',
  // 'site-manager-training-email-template',
  // 'spec-template',
  // 'sustainalytics',
  // 'switching-a-site-from-manual-to-usync',
  // 'system-methodologies-for-conversions-ghg-green-house-gas-estimates',
  // 'template-emails',
  // 'template-for-non-latin-ocrardem-requirements',
  // 'the-difference-between-estar-and-msr-uploads',
  // 'ticket-tags-checkboxes',
  // 'tips-tricks-for-success-in-customer-success',
  // 'top-100-real-estate-targets',
  // 'touchpoints-wcustomers',
  // 'troubleshooting-user-issues',
  // 'ul-ehs-pure',
  // 'uli',
  // 'unknown-accounts-site-blacklist',
  // 'upcoming-campaign-proposed-timelineactivities',
  // 'upfront-contracts-call-1-call-2',
  // 'urjanet-measurabl-meetings-video-recordings',
  // 'using-the-hello-videoconferencing-cameras',
  //
  'usync-data-modification-utility-bill-measurabl',
  'usync-pre-requisites-for-data-extraction',
  'utility-sync-customer-issues',
  'utility-sync-kpis',
  'utility-sync-on-boarding-process',
  'utility-sync-qa-plan',
  'utility-sync-strategy-nikks-recommendations',
  'utility-sync-tasks',
  'utility-sync-technical-processes-know-how',
  'utility-sync-weekly-email-process',
  'utility-vendors-not-supported-by-utilitysync',
  'value-propositions-conversation',
  'verdani',
  'vts-new-nav-webinar',
  'waste-support',
  'whitelisting-and-why',
  'wrap-up-of-on-boarding',
  'xcel-energy-extraction-discrepancies',
  'yardi-anomalous-data-review',
  'zen-desk-inbox-management',
  'zendesk-integrations',
  'zendesk-knowledge-base-statistics',
  'zendesk-ticket-practice-workflow',
  'zendesk-training-videos',
  'zoom-training-set-up-registration-recording'
];
describe('Tettra website tables', function () {

  function log(message) {
    cy.writeFile(Cypress.env('TABLES'), message + "\n", {flag: 'a+'});
  }

  it('should be able to search for page tables', function () {
    cy.exec(`touch ${Cypress.env('TABLES')} && rm ${Cypress.env('TABLES')}`);
    cy
      .visit(Cypress.env('TETTRA'))
      .get('h1').contains('Sign in to your team')
      .get('#email').type(Cypress.env('EMAIL'))
      .get('#password').type(Cypress.env('PASSWORD'))
      .get('input[type=submit]').click()
      .url().should('contain', Cypress.env('SPACE'));

    log('page|divs|images|tables');
    pages.forEach(page => {
      const url = `https://app.tettra.co/teams/measurabl/pages/${page}`;
      cy.visit(url);
      cy.get('div[data-contents="true"]').then($el => {
          const divs = $el.find('div').length;
          const images = $el.find('img').length;
          const tables = $el.find('table').length;
          log(`${url}|${divs}|${images}|${tables}`);
        }
      );
    });
  });
});
